# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
enable_free_tier: true

reviews:
  request_changes_workflow: true
  auto_review:
    enabled: true
    drafts: false

chat:
  integrations:
    jira:
      usage: disabled
    linear:
      usage: disabled

issue_enrichment:
  auto_enrich:
    enabled: true
